# Generated by Django 3.0.1 on 2020-06-01 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200601_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
