# Generated by Django 3.0.1 on 2020-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200601_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaveViewed',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('entry_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='company_id',
            new_name='check_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
    ]
