# Generated by Django 3.0.1 on 2020-06-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200602_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='boolAnswer',
            new_name='bool_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='unsafeAnswer',
            new_name='unsafe_answer',
        ),
    ]
