# Generated by Django 3.0.1 on 2020-06-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200602_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='unsafe_answer',
            new_name='notify',
        ),
        migrations.AddField(
            model_name='entry',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='bool_answer',
            field=models.BooleanField(default=True),
        ),
    ]
