# Generated by Django 3.0.1 on 2020-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200607_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
