# Generated by Django 3.0.1 on 2020-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200607_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='paid',
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='e@a.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
