# Generated by Django 3.0.1 on 2020-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200608_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='company_id',
            field=models.IntegerField(blank=True),
        ),
    ]
