# Generated by Django 3.0.1 on 2020-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200609_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_id',
            field=models.IntegerField(),
        ),
    ]
