# Generated by Django 3.0.1 on 2020-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200609_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
