# Generated by Django 3.0.1 on 2020-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200609_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
