# Generated by Django 3.0.1 on 2020-06-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200610_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
