# Generated by Django 3.0.1 on 2020-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_entry_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveviewed',
            old_name='check_id',
            new_name='check_number',
        ),
    ]
