# Generated by Django 3.0.1 on 2020-06-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200610_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
