# Generated by Django 3.0.1 on 2020-06-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200610_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='url_string',
            field=models.TextField(blank=True),
        ),
    ]
