# Generated by Django 3.0.1 on 2020-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200611_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('confirm_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('url_string', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
