# Generated by Django 3.0.1 on 2020-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200611_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
