# Generated by Django 3.0.1 on 2020-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200611_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCheck',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('deny', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='question_number',
        ),
        migrations.AddField(
            model_name='check',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
