# Generated by Django 3.0.1 on 2020-06-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200612_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='check',
            name='last_name',
        ),
    ]
