# Generated by Django 3.0.1 on 2020-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200615_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
