# Generated by Django 3.0.1 on 2020-06-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_company_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCheck',
        ),
        migrations.DeleteModel(
            name='VerifyCompany',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='user_id',
            new_name='client_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='admin',
        ),
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
