# Generated by Django 3.0.1 on 2020-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200616_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientString',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_string', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='client_number',
        ),
    ]
