# Generated by Django 3.0.1 on 2020-06-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200617_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='question',
        ),
        migrations.AddField(
            model_name='entry',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
