# Generated by Django 3.0.1 on 2020-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200617_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveSearch',
        ),
        migrations.DeleteModel(
            name='SaveViewed',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='medical',
            new_name='personal',
        ),
        migrations.RemoveField(
            model_name='check',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='active',
        ),
        migrations.AlterField(
            model_name='check',
            name='completed_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
