# Generated by Django 3.0.1 on 2020-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200617_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bool_answer',
            field=models.BooleanField(default=False),
        ),
    ]
