# Generated by Django 3.0.1 on 2020-06-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_entry_bool_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='bool_answer',
        ),
    ]
